package com.hk.dao;

import com.hk.model.SysPermisson;

public interface SysPermissonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permisson
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permisson
     *
     * @mbg.generated
     */
    int insert(SysPermisson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permisson
     *
     * @mbg.generated
     */
    int insertSelective(SysPermisson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permisson
     *
     * @mbg.generated
     */
    SysPermisson selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permisson
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysPermisson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permisson
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysPermisson record);
}